export const itemPalletInfoList = [
  {
    _id: 'afasdfjuasdfj',
    ibm: '123456',
    alias: 'rc02569',
    uof: 'PL',
    count: 7,
    ti: 9,
    hi: 25,
    partial: 0,
    status: 'LODGING',
  },
  {
    _id: 'afasdfjfdgsuasdfj',
    ibm: '123405',
    alias: 'rc02549',
    uof: 'PL',
    count: 25,
    ti: 5,
    hi: 10,
    partial: 12,
    status: 'LODGING',
  },
  {
    _id: 'afasdfasdfasdfjuasdfj',
    ibm: '523455',
    alias: 'rf02569',
    uof: 'P1',
    count: 9,
    ti: 9,
    hi: 25,
    partial: 10,
    status: 'LODGING',
  },
  {
    _id: 'afaafasdfasdfjuasdfj',
    ibm: '322456',
    alias: 'rc02569',
    uof: 'PL',
    count: 10,
    ti: 14,
    hi: 7,
    partial: 0,
    status: 'LODGING',
  },
  {
    _id: 'afasdfjuaasdfasdfj',
    ibm: '503456',
    alias: 'rc22569',
    uof: 'PL',
    count: 10,
    ti: 10,
    hi: 7,
    partial: 25,
    status: 'DONE',
  },
  {
    _id: 'afasdfjuasdfadfadsfj',
    ibm: '650000',
    alias: 'rc02569',
    uof: 'P1',
    count: 10,
    ti: 6,
    hi: 5,
    partial: 0,
    status: 'DONE',
  },
];
